# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 29))
        self.menubar.setObjectName("menubar")
        self.btn_train = QtWidgets.QMenu(self.menubar)
        self.btn_train.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        self.btn_train.setFont(font)
        self.btn_train.setObjectName("btn_train")
        self.btn_detect = QtWidgets.QMenu(self.menubar)
        self.btn_detect.setObjectName("btn_detect")
        self.btn_labeling = QtWidgets.QMenu(self.menubar)
        self.btn_labeling.setObjectName("btn_labeling")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_new = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.action_new.setFont(font)
        self.action_new.setObjectName("action_new")
        self.action_import = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.action_import.setFont(font)
        self.action_import.setObjectName("action_import")
        self.action_delete = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.action_delete.setFont(font)
        self.action_delete.setObjectName("action_delete")
        self.btn_train.addAction(self.action_new)
        self.btn_train.addAction(self.action_import)
        self.btn_train.addAction(self.action_delete)
        self.menubar.addAction(self.btn_train.menuAction())
        self.menubar.addAction(self.btn_detect.menuAction())
        self.menubar.addAction(self.btn_labeling.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "深度学习训练模型"))
        self.btn_train.setTitle(_translate("MainWindow", "训练模型"))
        self.btn_detect.setTitle(_translate("MainWindow", "检测数据"))
        self.btn_labeling.setTitle(_translate("MainWindow", "数据标注"))
        self.action_new.setText(_translate("MainWindow", "新建训练工程"))
        self.action_import.setText(_translate("MainWindow", "导入已有工程"))
        self.action_delete.setText(_translate("MainWindow", "删除训练工程"))
